flowchart TD
    %% Actors
    subgraph defendants
        mc[Magnus Carlsen]
        playmagnus[Play Magnus Group]
        chesscom[Chess.com]
        naka[Hikaru Nakamura]

        mc --Owns majority--> playmagnus
        playmagnus <--Merger talks--> chesscom
        chesscom --Sponsoring--> naka
    end

    hans[Hans Niemann]

    %% Accusations
    hans --sueing for $100M--> defendants

    %% Offense
    naka --Accused of cheating on his stream--> hans
    mc --Lost then withdrew with accusations--> hans
    chesscom --72 page report of cheating--> hans
    