@startuml
' Actors
"Hans Niemann" as hans

rectangle "defendants" {
  "Magnus Carlsen" as mc
  "Play Magnus Group" as playmagnus
  "Chess.com" as chesscom
  "Hikaru Nakamura" as naka

  mc -> playmagnus: Owns majority
  playmagnus <-> chesscom: Merger talks
  chesscom -> naka: Sponsoring
}

' Accusations
hans -> defendants: suing for $100M

' Offense
naka --> hans : Accused of cheating on his stream
mc --> hans : Lost then withdrew with accusations
chesscom --> hans: 72 page report of cheating
@enduml
