description: |md
  # Hope is a good breakfast, but it is a bad supper

  - Look into my eyes and try to forget that you have a Macy's charge card!
  - The **Tree of Learning** bears the noblest fruit, but noble fruit tastes bad.

  "There is nothing new under the sun, but there are lots of old things
  we don't know yet."
    - *Ambrose Bierce*
|
description -> x
